/**
 * Migration honesty tests.
 *
 * The old version of this file grepped the migration SQL as text
 * ("create policy", "security definer", …). Those assertions are now
 * executed against a real throwaway Postgres instead:
 * scripts/verify-db.mjs applies every migration in order (twice, for the
 * idempotent range) and runs supabase/tests/*.test.sql, which assert the
 * RLS posture, the RPC surface, and the seeded rows against the live
 * catalogs. See supabase/tests/schema_contract.test.sql.
 */
import { cpSync, mkdtempSync, readdirSync, rmSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { GAME_SKILL_CODES } from '@/lib/kid/game-skills';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migDir = join(root, 'supabase', 'migrations');

describe('migration files', () => {
  it('are complete and strictly ordered', () => {
    const files = readdirSync(migDir)
      .filter((f) => f.endsWith('.sql'))
      .sort();
    // Pinned: a new migration must update this list deliberately.
    expect(files).toEqual([
      '20260924000100_core.sql',
      '20260924000200_taxonomy.sql',
      '20260924000300_activity_bank.sql',
      '20260924000400_learning.sql',
      '20260924000500_storage.sql',
      '20260924000600_pgcrypto_search_path.sql',
      '20260925000100_fix_choice_grading.sql',
      '20260925000200_sticker_awards.sql',
      '20260925000300_content_refresh.sql',
      '20260925000400_trail_streaks.sql',
      '20260925000500_pets.sql',
      '20260925000600_outfits.sql',
      '20260925000700_wallet_rpc.sql',
      '20260925000800_trophies.sql',
      '20260925000900_parent_goals.sql',
      '20260925001000_collections.sql',
      '20260925001100_cleanup_dead_schema.sql',
      '20260925001200_fix_ensure_parent_profile.sql',
      '20260926000100_game_learning.sql',
      '20260926000200_content_quality.sql',
    ]);
  });
});

function localPostgresAvailable(): boolean {
  try {
    execFileSync(
      'su',
      [
        'postgres',
        '-c',
        `psql 'postgres:///postgres?host=/var/run/postgresql' -t -c 'select 1'`,
      ],
      { timeout: 15000, stdio: 'pipe' }
    );
    return true;
  } catch {
    return false;
  }
}

const canVerifyDb = localPostgresAvailable();

describe('migrations against a real Postgres', () => {
  it.skipIf(!canVerifyDb)(
    'apply cleanly (idempotent re-apply) and satisfy the schema contract',
    () => {
      // The postgres OS user cannot traverse the repo's home directories,
      // so stage a world-readable copy of the script + migrations + tests.
      const stage = mkdtempSync(join(tmpdir(), 'sky-verify-'));
      try {
        cpSync(join(root, 'scripts'), join(stage, 'scripts'), {
          recursive: true,
        });
        cpSync(join(root, 'supabase'), join(stage, 'supabase'), {
          recursive: true,
        });
        // Behavioral cross-check the static tests cannot do: every skill code
        // the games can report must be accepted by the real
        // record_game_attempts (unknown codes raise and drop the batch).
        // Appended inside game_learning.test.sql's transaction so the
        // fixtures and auth context are in place.
        const sweepPath = join(stage, 'supabase', 'tests', 'game_learning.test.sql');
        const codes = GAME_SKILL_CODES.map((c) => `'${c}'`).join(',');
        const sweep = `
-- ---- generated by tests/migrations.test.ts: skill-code acceptance sweep --
-- (the file's tail runs as anon for permission tests; switch back)
reset role;
set local role authenticated;
set local request.jwt.claim.sub = '00000000-0000-0000-0000-00000000000a';
do $$
declare
  r jsonb;
begin
  r := public.record_game_attempts(
    '00000000-0000-0000-0000-0000000000c1', 'skill-sweep',
    (select jsonb_agg(jsonb_build_object('skill', code, 'correct', true, 'level', 1))
     from unnest(array[${codes}]) as code));
  assert (r ->> 'recorded')::int = ${GAME_SKILL_CODES.length},
    format('skill sweep recorded %s of %s codes', r ->> 'recorded', ${GAME_SKILL_CODES.length});
end $$;
`;
        const sql = readFileSync(sweepPath, 'utf8');
        // Replacer function (not a string): String.replace interprets $$
        // in a string replacement as an escaped $, which would mangle the
        // do $$ blocks.
        writeFileSync(
          sweepPath,
          sql.replace(/rollback;\s*$/, () => `${sweep}\nrollback;\n`)
        );
        execFileSync('chmod', ['-R', 'a+rX', stage]);
        const out = execFileSync(
          'su',
          [
            'postgres',
            '-c',
            `env DATABASE_URL='postgres:///postgres?host=/var/run/postgresql' ${process.execPath} ${join(stage, 'scripts', 'verify-db.mjs')}`,
          ],
          { timeout: 600000, encoding: 'utf8', stdio: 'pipe' }
        );
        expect(out).toContain('migrations applied (pass 1)');
        expect(out).toContain('migrations applied (pass 2)');
        expect(out).toContain('ok   schema_contract.test.sql');
        expect(out).toContain('ok   content_quality.test.sql');
        expect(out).toContain('ok   game_learning.test.sql');
      } finally {
        rmSync(stage, { recursive: true, force: true });
      }
    },
    600000
  );

  it.skipIf(canVerifyDb)('reports when local Postgres is unavailable', () => {
    // Placeholder so the skip is visible instead of silent.
    expect(canVerifyDb).toBe(false);
  });
});

describe('avatar roster', () => {
  it('matches between the lib list and the visual registry', async () => {
    // The DB seed side is asserted in schema_contract.test.sql (8 rows).
    const { AVATAR_IDS } = await import('@/lib/avatars');
    const { AVATARS } = await import('@/components/avatars/index');
    expect(AVATAR_IDS).toHaveLength(8);
    expect([...AVATAR_IDS].sort()).toEqual(Object.keys(AVATARS).sort());
  });
});
