#!/usr/bin/env python3
"""Sky Phase 3 activity bank generator — the content rethink.

Every activity is a moment in an ongoing story (see story_bible.md):
narrative hooks, host character voices, recurring story friends,
misconception-based distractors, and level arcs.

Outputs:
  supabase/seed_phase3.sql   - full replacement bank (run AFTER the
                               content-refresh migration deletes the old bank)
  supabase/seed_phase3.json  - manifest of the same activities
  supabase/migrations/20260925000300_content_refresh.sql - DELETEs the old
                               bank and inserts the new one (idempotent)

Deterministic: fixed RNG seed, reproducible output.
"""
import datetime
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from core import ACTS, AGES, validate  # noqa: E402

from content import reading, writing, math, science, geography  # noqa: E402
from content import coding, music, drawing, feelings  # noqa: E402

SUPABASE = HERE.parent
OUT_SQL = SUPABASE / "seed_phase3.sql"
OUT_JSON = SUPABASE / "seed_phase3.json"
OUT_MIGRATION = SUPABASE / "migrations" / "20260925000300_content_refresh.sql"


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    for module in (reading, writing, math, science, geography,
                   coding, music, drawing, feelings):
        module.build()

    errors = validate()
    if errors:
        print("VALIDATION FAILED:")
        for e in errors[:30]:
            print("  -", e)
        sys.exit(1)

    # ---- seed_phase3.json (manifest) ----
    OUT_JSON.write_text(json.dumps(ACTS, indent=1, ensure_ascii=False))
    print(f"wrote {OUT_JSON} ({len(ACTS)} activities)")

    # ---- seed_phase3.sql (standalone seed) ----
    lines = [
        "-- Sky Phase 3 activity bank seed. Generated by",
        "-- supabase/seed_generators/bank_phase3.py — the content rethink.",
        "-- Full replacement bank: every skill x every level, story-driven.",
        "-- Run AFTER the 20260925000300_content_refresh migration (or on a",
        "-- fresh DB after seed.sql). Idempotent on full content identity.",
        "",
    ]
    for a in ACTS:
        card = sql_escape(json.dumps(a["card"], ensure_ascii=False))
        answer = sql_escape(json.dumps(a["answer"], ensure_ascii=False))
        prompt = sql_escape(a["prompt_text"])
        lines.append(
            "INSERT INTO public.activities "
            "(skill_id, level, kind, prompt_text, card, answer, points, "
            "min_age_band, max_age_band)\n"
            f"SELECT s.id, {a['level']}, '{a['kind']}', '{prompt}', "
            f"'{card}'::jsonb, '{answer}'::jsonb, {a['points']}, "
            f"'{a['min_age_band']}', '{a['max_age_band']}'\n"
            f"FROM public.skills s WHERE s.code = '{a['skill']}'\n"
            f"AND NOT EXISTS (SELECT 1 FROM public.activities x "
            f"WHERE x.skill_id = s.id AND x.prompt_text = '{prompt}');\n"
        )
    OUT_SQL.write_text("\n".join(lines))
    print(f"wrote {OUT_SQL}")

    # ---- migration: replace the old bank ----
    today = datetime.date.today().isoformat()
    mig = [
        f"-- Sky Phase 3 content refresh ({today}).",
        "-- Replaces the Phase 1/2 worksheet-style activity bank with the",
        "-- story-driven Phase 3 bank. learning_events.activity_id is",
        "-- ON DELETE SET NULL, so history keeps skill_id + metadata.",
        "-- Idempotent: safe to re-run.",
        "",
        "BEGIN;",
        "",
        "-- 1. Remove the old bank.",
        "DELETE FROM public.activities;",
        "",
    ]
    for a in ACTS:
        card = sql_escape(json.dumps(a["card"], ensure_ascii=False))
        answer = sql_escape(json.dumps(a["answer"], ensure_ascii=False))
        prompt = sql_escape(a["prompt_text"])
        mig.append(
            "INSERT INTO public.activities "
            "(skill_id, level, kind, prompt_text, card, answer, points, "
            "min_age_band, max_age_band)\n"
            f"SELECT s.id, {a['level']}, '{a['kind']}', '{prompt}', "
            f"'{card}'::jsonb, '{answer}'::jsonb, {a['points']}, "
            f"'{a['min_age_band']}', '{a['max_age_band']}'\n"
            f"FROM public.skills s WHERE s.code = '{a['skill']}'\n"
            f"AND NOT EXISTS (SELECT 1 FROM public.activities x "
            f"WHERE x.skill_id = s.id AND x.prompt_text = '{prompt}');\n"
        )
    mig.append("COMMIT;\n")
    OUT_MIGRATION.write_text("\n".join(mig))
    print(f"wrote {OUT_MIGRATION}")

    # ---- coverage report ----
    from collections import Counter
    counts = Counter((a["skill"], a["level"]) for a in ACTS)
    kinds = Counter(a["kind"] for a in ACTS)
    print(f"\nTotal: {len(ACTS)} activities, "
          f"{len(counts)} skill/level pairs")
    print("Kinds:", dict(kinds))


if __name__ == "__main__":
    main()
